site_name: SRUSA Portal
site_description: SRUSA の情報をまとめるポータルサイト

theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search:
      lang: ja

nav:
  - ホーム: index.md
  - 登山部:
      - 登山部: mountaineering/index.md
      - 活動記録:
          - 大菩薩嶺（2026年7月4日）: mountaineering/活動記録/20260704.md
  - Minecraft: minecraft/index.md

strict: true
