site_name: SRUSA Portal
site_description: SRUSA の情報をまとめるポータルサイト

theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

plugins:
  - search:
      lang: ja

strict: true
